name: Insidemovie-AI
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=17.0.6=he5c5206_4
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.16=h02f6b3c_0
  - pip=25.1=pyhc872135_2
  - python=3.12.11=h421de30_0
  - readline=8.2=h1a28f6b_0
  - setuptools=78.1.1=py312hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_1
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - click==8.2.1
      - dnspython==2.7.0
      - fastapi==0.116.1
      - filelock==3.18.0
      - fsspec==2025.5.1
      - h11==0.16.0
      - hf-xet==1.1.5
      - huggingface-hub==0.33.4
      - httpx==0.28.1
      - idna==3.10
      - jinja2==3.1.6
      - kobert-tokenizer==0.1
      - markupsafe==3.0.2
      - motor==3.7.1
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.1
      - packaging==25.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pymongo==4.13.2
      - pytest==8.3.4
      - python-dotenv==1.1.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - starlette==0.47.1
      - sympy==1.14.0
      - tokenizers==0.21.2
      - torch==2.7.1
      - tqdm==4.67.1
      - transformers==4.53.2
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - uvicorn==0.35.0
